name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      env:
        modified: ${{ github.event.head_commit.modified }}

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
