name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Listar modificados
      run: echo "${{ github.event.head_commit.modified }}"

    - name: Listar removidos
      run: echo "${{ github.event.head_commit.removed }}"

    - name: Listar adicionados
      run: echo "${{ github.event.head_commit.added }}"

    # - name: Start containers
    #   run: docker-compose -f "docker-compose.yml" up -d --build

    # - name: Stop containers
    #   if: always()
    #   run: docker-compose -f "docker-compose.yml" down
