name: Test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  docker:
    timeout-minutes: 10
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Alterações
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          src:
            - '**'

    - name: Exibir
      if: steps.changes.outputs.src == 'true'
      run: echo "${{ steps.changes.outputs.src_files }}"

    # - name: Start containers
    #   run: docker-compose -f "docker-compose.yml" up -d --build

    # - name: Stop containers
    #   if: always()
    #   run: docker-compose -f "docker-compose.yml" down
