name: Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      env:
        commit: ${{ github.event.head_commit }}

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down
